### ISSUE TITLE
CITEseq data?

### ISSUE THREAD

**Issue by sorjuela** [LTLA/scRNAseq#16]
Hi @LTLA,

I was thinking of doing something like your package but with CITE/REAPseq data. But I'm wondering if it makes more sense to just add them to this package, and expand the `create_sce` function to accept a third matrix with the ADT counts.

Another package would have the same scheme as this one, so I guess it's also fine? what do you think?

Best,
Stephany

**Comment by LTLA** [comment]
Sure. Or you could even save them as two separate SCEs and then assemble them together in the function. Open a PR with a `.Rmd` file with the same structure as the ones that already exist in `inst/scripts/2.4.0` and we can have a look.

**Comment by LTLA** [comment]
Closed by #17.
