### ISSUE TITLE
It is possible to add a scRNA-seq data to your package?

### ISSUE THREAD

**Issue by kaanokay** [LTLA/scRNAseq#37]
Hi,

First of all, I'd like to thank you for this awesome R package. I'm wondering whether you can make a data as reference data in your package. Data is available in this link (https://doi.org/10.1016/j.neuron.2021.10.036). It compromise single-nucleus RNA-seq of adult hippocampal-entorhinal cells in human, monkey, and pig; however, transcriptomic signatures of adult neurogenesis in mouse, pig, and monkey but not human. If it possible to add this data, it gonna be super amazing for scientist who is working on primate neurogenesis.

Thank a lot.
Best regards.

**Comment by LTLA** [comment]
I don't have the time to do this myself but would be willing to consider a PR.

**Comment by kaanokay** [comment]
I see. Thanks.
