### ISSUE TITLE
Open to hosting the CellBench data?

### ISSUE THREAD

**Issue by PeteHaitch** [LTLA/scRNAseq#4]
We're looking for a more 'official' Bioconductor home for the CellBench data (https://github.com/LuyiTian/CellBench_data).
Would you be happy to receive a PR that follows the guidelines in https://bioconductor.org/packages/devel/data/experiment/vignettes/scRNAseq/inst/doc/scRNAseq.html#adding-new-data-sets?
The proposed function would be:

```R
TianCellBenchData(which=c("sc_10x", "sc_celseq", "sc_dropseq",
                          "cell_mix1", "cell_mix2", "cell_mix3", "cell_mix4", "cell_mix5",
                          "mrna_mix_celseq", "mrna_mix_sortseq")
```
FYI it does include some processed 10x data.

Tagging in @Shians, @LuyiTian, and @mritchie

**Comment by LTLA** [comment]
Knock yourself out.

**Comment by LTLA** [comment]
Is this happening anytime soon?

**Comment by PeteHaitch** [comment]
Yes.
@shians is currently doing paper revisions for it, which it'll be a part of.

**Comment by LTLA** [comment]
Tick tock.

**Comment by LTLA** [comment]
I guess this never happened. Reopen when you have a PR.
