### ISSUE TITLE
Unable to access package functions properly

### ISSUE THREAD

**Issue by gnvalbuena** [LTLA/scRNAseq#52]
Hi,

I've just installed the scRNAseq package as per instructions on bioconductor, and I seem to be getting namespace issues I don't entirely understand the cause of.

I've got `scRNAseq_2.16.0` installed and loaded on `R version 4.3.2`, but when I try to run the following:

```
library(scRNAseq)
searchDatasets("brain")[,c("name", "title")]
```

I get the error message `Error in searchDatasets("brain") : 
  could not find function "searchDatasets"`

And when I try

```
library(scRNAseq)
all.ds <- scRNAseq::surveyDatasets()
```

I get the error message `Error: 'surveyDatasets' is not an exported object from 'namespace:scRNAseq'`.

How do I resolve this given that these functions are pretty much fundamental to getting the package working?

Thanks!

Best,
Gabriel

**Comment by LTLA** [comment]
I assume you're looking at the latest instructions on the [landing page](https://bioconductor.org/packages/scRNAseq), which correspond to version 2.18.0 of the package. The older versions don't have `surveyDatasets` and friends, just `scRNAseq::listDatasets()`.
