### ISSUE TITLE
DataFrame Conversion Error

### ISSUE THREAD

**Issue by DarioS** [LTLA/scRNAseq#56]
Attempting to convert to `data.frame` to view the data set summary table interactively in RStudio Server using `View(datasets)`:

```r
library(scRNAseq)
as.data.frame(surveyDatasets())
# Error in as.vector(x, mode = "character") : 
#   no method for coercing this S4 class to a vector

> sessionInfo()
R version 4.4.0 (2024-04-24)
Platform: x86_64-pc-linux-gnu
Running under: Debian GNU/Linux 12 (bookworm)

other attached packages:
  scRNAseq_2.19.1             SingleCellExperiment_1.27.2 SummarizedExperiment_1.35.1 Biobase_2.65.0
  GenomicRanges_1.57.1        GenomeInfoDb_1.41.1         IRanges_2.39.2              S4Vectors_0.43.2           
  BiocGenerics_0.51.0         MatrixGenerics_1.17.0       matrixStats_1.3.0 
```

**Comment by PeteHaitch** [comment]
Not sure what you want to happen here.
Columns 7 onwards in the object returned by `surveyDatasets()` have complex structure (_List_ and even _SplitDataFrameist_) to accommodate the one-to-many relationship for that row.
You can view the 'simple' data with `View(as.data.frame(surveyDatasets()[, 1:6]))`

**Comment by DarioS** [comment]
Aha!
