### ISSUE TITLE
Versions Not Following Bioconductor System

### ISSUE THREAD

**Issue by DarioS** [LTLA/scRNAseq#7]
The release version is 1.99.8 but the development version is 2.1.1. Version 2.0.* seems to have been skipped somehow.

**Comment by LTLA** [comment]
I suspect that's because the release version hasn't gotten around to being rebuilt yet. @lshep might have some more comments.

**Comment by lshep** [comment]
I would've expected them to have built Sunday. We will check the logs and keep an eye on tomorrow's build of the experiment packages.

**Comment by lshep** [comment]
I think this should be corrected now as the data experiment packages rebuilt last night -  Please let me know if there are further issues

**Comment by LTLA** [comment]
Well, it's still breaking on release for connectivity reasons:

http://bioconductor.org/checkResults/release/data-experiment-LATEST/scRNAseq/malbec1-checksrc.html

**Comment by LTLA** [comment]
2.0.1 has built successfully.
